version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: controle_financeiro_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: controle_financeiro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - controle_net

  mongodb:
    image: mongo:latest
    container_name: controle_financeiro_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - controle_net

volumes:
  postgres_data:
  mongo_data:

networks:
  controle_net:
